# Generated by Django 3.1.4 on 2021-01-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210105_0419'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=100)),
                ('book_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Donate Books',
            },
        ),
    ]
