# Generated by Django 3.1.4 on 2021-01-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_donatebooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('todo_item', models.CharField(max_length=100)),
                ('week', models.CharField(max_length=100)),
            ],
        ),
    ]
